[project]
name = "modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9.4",
 "dbt-duckdb>=1.9.3",
 "dbt-postgres>=1.9.0",
 "sqlfluff>=3.4.0",
]
