version: 2

models:
  - name: f_book_inventory
    description: >
      Snapshot fact table capturing the daily inventory state of books.
      Includes current unit price and available stock as of each date.
    columns:
      - name: date_sk
        description: Foreign key to d_date dimension.
        tests:
          - not_null
          - relationships:
              field: date_sk
              to: ref('d_date')
      - name: book_sk
        description: Foreign key to d_books dimension.
        tests:
          - not_null
          - relationships:
              field: book_sk
              to: ref('d_books')
      - name: unit_price
        description: Unit price of the book on that date.
      - name: stock
        description: Number of items in stock on that date.

  - name: f_order_item_transactions
    description: >
      Fact table capturing order item events with temporal alignment to 
      slowly changing dimensions. Includes customer, order, and book references 
      at the time of the transaction.
    columns:
      - name: order_item_event_sk
        description: Surrogate key for the order item event.
        tests:
          - not_null
          - unique
      - name: order_sk
        description: Foreign key to d_orders (SCD 2).
        tests:
          - not_null
          - relationships:
              field: order_sk
              to: ref('d_orders')
      - name: customer_sk
        description: Foreign key to d_customers (SCD 2).
        tests:
          - not_null
          - relationships:
              field: customer_sk
              to: ref('d_customers')
      - name: book_sk
        description: Foreign key to d_books (SCD 0).
        tests:
          - not_null
          - relationships:
              field: book_sk
              to: ref('d_books')
      - name: date_sk
        description: Foreign key to d_date (date of transaction).
        tests:
          - not_null
          - relationships:
              field: date_sk
              to: ref('d_date')
      - name: transaction_time
        description: Timestamp of the transaction.
      - name: quantity
        description: Number of units purchased in the order item.
      - name: price_at_purchase
        description: Price per unit at the time of purchase.
      - name: discount
        description: Discount applied at the time of purchase.

  - name: f_shipment_events
    description: >
      Transactional fact table capturing individual shipment events.
      Each record reflects a shipping update including tracking info,
      cost, status, and delivery timestamps. This table is time-variant
      and aligns with SCD2 dimensions for orders and carrier services.
    columns:
      - name: shipment_event_sk
        description: Surrogate primary key for the shipment event.
        tests:
          - not_null
          - unique
      - name: shipment_sk
        description: Foreign key to the d_shipments dimension.
        tests:
          - not_null
          - relationships:
              field: shipment_sk
              to: ref('d_shipments')
      - name: order_sk
        description: Foreign key to the d_orders dimension (SCD2).
        tests:
          - not_null
          - relationships:
              field: order_sk
              to: ref('d_orders')
      - name: carrier_service_sk
        description: Foreign key to the d_carrier_services dimension (SCD2).
        tests:
          - not_null
          - relationships:
              field: carrier_service_sk
              to: ref('d_carrier_services')
      - name: transaction_time
        description: Timestamp of the shipment event.
        tests:
          - not_null
      - name: tracking_number
        description: Tracking number assigned to the shipment.
      - name: shipping_cost
        description: Cost of the shipment for the order.
      - name: shipping_status
        description: Status of the shipment (e.g., shipped, in transit, delivered).
      - name: shipped_date
        description: Date when the shipment was dispatched.
      - name: expected_delivery_date
        description: Date the shipment is expected to be delivered.
      - name: actual_delivery_date
        description: Date the shipment was actually delivered.
